#include<iostream>
using namespace std;
int main()
{
    int a,b;
    cout<<"enter a :";
    cin>>a;
    cout<<"enter b :";
    cin>>b;

    cout<<"\n value a:"<<a;
    cout<<"\n value b:"<<b;
    cout<<"\n sizeof int :"<<sizeof(int);

    cout<<"\n add a:"<<&a;
    cout<<"\n add b:"<<&b;

   /* cout<<"\n Enter a & b:";
    cin>>a>>b;

    cout<<"\n value a: \t b:"<<a<<b;
    cout<<"\n add a: \t b:"<<a<<b;*/

    return 0;
}