#include<iostream>
using namespace std;
int main()
{
    char ch='A',ch1='Z',ch2='a';
    int ch3=122;
   /* cout<<"\n char :"<<ch;
    cout<<"\n value :"<<ch;
    cout<<"\n char :"<<ch1;
    cout<<"\n value :"<<ch1;
    cout<<"\n char :"<<ch2;
    cout<<"\n value :"<<ch2;
    cout<<"\n char :"<<ch3;
    cout<<"\n value :"<<ch3;*/

    cout<<"\n char :"<<ch;
    cout<<"\n value :"<<ch;
    cout<<"\n char :"<<ch+25;
    cout<<"\n value :"<<ch+25;
    cout<<"\n char :"<<ch+32;
    cout<<"\n value :"<<ch+32;
    cout<<"\n char :"<<ch+32+25;
    cout<<"\n value :"<<ch+32+25;
    return 0;
}